### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 89z** [mewrev/pe#2]
It seems because no license is listed, that documentation is not available:

https://pkg.go.dev/github.com/mewrev/pe

**Comment by 89z** [comment]
my mistake looks like was moved here:

https://pkg.go.dev/github.com/mewmew/pe

**Comment by 89z** [comment]
Hm, what is this?

https://github.com/mewmew/pe

**Comment by mewmew** [comment]
Hi @89z,

Thanks for the notice.

I've now added the public domain attribution to the repository.

Cheers,
Robin

**Comment by 89z** [comment]
Thank you very much!
